=== wjluo/petshop/admin/xml/orders_products.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT data (order+,popular_product+)>
<!ELEMENT order (order_id,firstname,lastname,total_cost)>
<!ELEMENT popular_product (product_id,name,product_total_sell_quantity)>
<!ELEMENT order_id (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT total_cost (#PCDATA)>
<!ELEMENT product_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT product_total_sell_quantity (#PCDATA)>

=== wjluo/petshop/admin/xml/orders_products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "orders_products.dtd">
<data>
  <order>
    <order_id>14</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>66.91</total_cost>
  </order>
  <order>
    <order_id>27</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>57.97</total_cost>
  </order>
  <order>
    <order_id>5</order_id>
    <firstname>Γιώργος</firstname>
    <lastname>Παπαδόπουλος</lastname>
    <total_cost>47.35</total_cost>
  </order>
  <order>
    <order_id>1</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>44.1</total_cost>
  </order>
  <order>
    <order_id>30</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>38.8</total_cost>
  </order>
  <order>
    <order_id>12</order_id>
    <firstname>Ιωάννα</firstname>
    <lastname>Παυλίδου</lastname>
    <total_cost>38.6</total_cost>
  </order>
  <order>
    <order_id>2</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>36.94</total_cost>
  </order>
  <order>
    <order_id>7</order_id>
    <firstname>Γιώργος</firstname>
    <lastname>Παπαδόπουλος</lastname>
    <total_cost>33.9</total_cost>
  </order>
  <order>
    <order_id>3</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>33.67</total_cost>
  </order>
  <order>
    <order_id>13</order_id>
    <firstname>Ιωάννα</firstname>
    <lastname>Παυλίδου</lastname>
    <total_cost>29.38</total_cost>
  </order>
  <order>
    <order_id>8</order_id>
    <firstname>Στέλλα</firstname>
    <lastname>Ιωαννίδου</lastname>
    <total_cost>18.7</total_cost>
  </order>
  <order>
    <order_id>10</order_id>
    <firstname>Στέλλα</firstname>
    <lastname>Ιωαννίδου</lastname>
    <total_cost>17.91</total_cost>
  </order>
  <order>
    <order_id>15</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>17.46</total_cost>
  </order>
  <order>
    <order_id>4</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>17</total_cost>
  </order>
  <order>
    <order_id>11</order_id>
    <firstname>Στέλλα</firstname>
    <lastname>Ιωαννίδου</lastname>
    <total_cost>16.2</total_cost>
  </order>
  <order>
    <order_id>9</order_id>
    <firstname>Στέλλα</firstname>
    <lastname>Ιωαννίδου</lastname>
    <total_cost>13.5</total_cost>
  </order>
  <order>
    <order_id>29</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>11.47</total_cost>
  </order>
  <order>
    <order_id>6</order_id>
    <firstname>Γιώργος</firstname>
    <lastname>Παπαδόπουλος</lastname>
    <total_cost>9.7</total_cost>
  </order>
  <order>
    <order_id>26</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>9.7</total_cost>
  </order>
  <order>
    <order_id>25</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>3.3</total_cost>
  </order>
  <order>
    <order_id>28</order_id>
    <firstname>Demo</firstname>
    <lastname>User</lastname>
    <total_cost>3.3</total_cost>
  </order>
  <popular_product>
    <product_id>2</product_id>
    <name>Royal Canin Dog Mini Adult Light</name>
    <product_total_sell_quantity>26</product_total_sell_quantity>
  </popular_product>
  <popular_product>
    <product_id>17</product_id>
    <name>Tasty Bone Nylon - Puppy</name>
    <product_total_sell_quantity>15</product_total_sell_quantity>
  </popular_product>
  <popular_product>
    <product_id>1</product_id>
    <name>Acana Puppy Small Breed</name>
    <product_total_sell_quantity>10</product_total_sell_quantity>
  </popular_product>
  <popular_product>
    <product_id>3</product_id>
    <name/>
    <product_total_sell_quantity>10</product_total_sell_quantity>
  </popular_product>
  <popular_product>
    <product_id>9</product_id>
    <name>Pet Camelot Περιλαίμιο Πνίχτης για Μακρύ Τρίχωμα</name>
    <product_total_sell_quantity>6</product_total_sell_quantity>
  </popular_product>
</data>
